name: Release

on:
  release:
    types: 
      - published

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - main
  workflow_dispatch:  # This line enables manual triggers from the GitHub UI

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tag
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "::set-output name=tag::${{ github.event.release.tag_name }}"
          else
            echo "::set-output name=tag::${{ github.ref_name }}"
          fi

      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/private-demo:${{ steps.set_tag.outputs.tag }}"
